export const Options = [

    {view_value:'Agartala (IXA)', value:'Maharaja Bir Bikram Airport (IXA)'},
    {view_value:'Amritsar (ATQ)', value:'Sri Guru Ram Dass Jee International Airport (ATQ)'},
    {view_value:'Belagavi (IXG)', value:'Belgaum Airport (IXG)'},
    {view_value:'Chandigarh (IXC)', value:'Chandigarh International Airport (IXC)'},
    {view_value:'Dehradun (DED)', value:' Jolly Grant Airport (DED)'},
    {view_value:'Hyderabad (HYD)', value:' Rajiv Gandhi International Airport (HYD)'},
    {view_value:'Agra (AGR)', value:'Pandit Deen Dayal Upadhyay Airport (AGR)'},
    {view_value:'Aurangabad (IXU)', value:'Aurangabad Airport (IXU)'},
    {view_value:'Bengaluru (BLR)', value:'Kempegowda International Airport (BLR)'},
    {view_value:'Delhi (DEL)', value:'Indira Gandhi International Airport (DEL)'},
    {view_value:'Guwahati (GAU)', value:'Lokpriya Gopinath Bordoloi International Airport (GAU)'},
    {view_value:'Jaipur (JAI)', value:'Jaipur International Airport (JAI)'},
    {view_value:'Mumbai (BOM)', value:'Chhatrapati Shivaji International Airport (BOM)'},
    {view_value:'Pune (PNQ)', value:'Pune International Airport (PNQ)'},
    {view_value:'Varanasi (VNS)', value:' Lal Bahadur Shastri International Airport (VNS)'},
    {view_value:'Ahmedabad (AMD)', value:' Sardar Vallabhbhai Patel International Airport (AMD)'},
    {view_value:'Bhopal (BHO)', value:' Raja Bhoj Airport (BHO)'},
    {view_value:'Gwalior (GWL)', value:'Gwalior Airport (GWL)'},
    {view_value:'Indore (IDR)', value:'Devi Ahilya Bai Holkar Airport (IDR)'},
    {view_value:'Jammu (IXJ)', value:'Jammu Airport (IXJ)'},
    {view_value:'Lucknow (LKO)', value:'Chaudhary Charan Singh International Airport (LKO)'},
    {view_value:'Goa (GOI)', value:'Goa International Airport (GOI)'},
    {view_value:'Kanpur (KNU)', value:' Chakeri Airport (KNU)'},
    {view_value:'Kozhikode (CCJ)', value:' Calicut International Airport (CCJ)'},
    {view_value:'Madurai (IXM)', value:'Madurai International Airport (IXM)'},
    {view_value:'Nagpur (NAG)', value:'Dr. Babasaheb Ambedkar International Airport (NAG)'},
    {view_value:'Shillong (SHL)', value:'Shillong Airport (SHL)'},
    {view_value:'Udaipur (UDR)', value:'Maharana Pratap Airport (UDR)'},
    {view_value:'Visakhapatnam (VTZ)', value:'Visakhapatnam International Airport (VTZ)'},
    {view_value:'Shirdi (SAG)', value:'Shirdi International Airport (SAG)'},
    {view_value:'Kolkata (CCU)', value:'Netaji Subhash Chandra Bose International Airport (CCU)'},
    {view_value:'Surat (STV)', value:'Surat International Airport (STV)'},
    {view_value:'Raipur (RPR)', value:'Swami Vivekananda International Airport (RPR)'},
    {view_value:'Bagdogra (IXB)', value:' Bagdogra Airport (IXB)'},
    {view_value:'Leh Airport (IXL)', value:'Kushok Bakula Rimpochee Airport (IXL)'},


]