export const Options = [
    'Agartala (IXA)',
    'Amritsar (ATQ)',
    'Belagavi (IXG)',
    'Chandigarh (IXC)',
    'Dehradun (DED)',
    'Hyderabad (HYD)',
    'Agra (AGR)',
    'Aurangabad (IXU)',
    'Bengaluru (BLR)',
    'Bengaluru (BLR)',
    'Delhi (DEL)',
    'Guwahati (GAU)',
    'Jaipur (JAI)',
    'Mumbai (BOM)',
    'Pune (PNQ)',
    'Varanasi (VNS)',
    'Ahmedabad (AMD)',
    'Bhopal (BHO)',
    'Gwalior (GWL)',
    'Indore (IDR)',
    'Jammu (IXJ)',
    'Lucknow (LKO)',
    'Goa (GOI)',
    'Kanpur (KNU)',
    'Kozhikode (CCJ)',
    'Madurai (IXM)',
    'Nagpur (NAG)',
    'Shillong (SHL)',
    'Udaipur (UDR)',
    'Visakhapatnam (VTZ)',
    'Shirdi (SAG)',
    'Kolkata (CCU)',
    'Surat (STV)'


]