export const Options = [

    {view_value:'Agartala (IXA)', value:'Agartala (IXA)-Maharaja Bir Bikram Airport'},
    {view_value:'Amritsar (ATQ)', value:'Amritsar (ATQ)-Sri Guru Ram Dass Jee International Airport'},
    {view_value:'Belagavi (IXG)', value:'Belagavi (IXG)-Belgaum Airport'},
    {view_value:'Chandigarh (IXC)', value:'Chandigarh (IXC)-Chandigarh International Airport'},
    {view_value:'Dehradun (DED)', value:'Dehradun (DED)-Jolly Grant Airport'},
    {view_value:'Hyderabad (HYD)', value:'Hyderabad (HYD)-Rajiv Gandhi International Airport'},
    {view_value:'Agra (AGR)', value:'Agra (AGR)-Pandit Deen Dayal Upadhyay Airport'},
    {view_value:'Aurangabad (IXU)', value:'Aurangabad (IXU)-Aurangabad Airport'},
    {view_value:'Bengaluru (BLR)', value:'Bengaluru (BLR)-Kempegowda International Airport'},
    {view_value:'Delhi (DEL)', value:'Delhi (DEL)-Indira Gandhi International Airport '},
    {view_value:'Guwahati (GAU)', value:'Guwahati (GAU)-Lokpriya Gopinath Bordoloi International Airport'},
    {view_value:'Jaipur (JAI)', value:'Jaipur (JAI)-Jaipur International Airport'},
    {view_value:'Mumbai (BOM)', value:'Mumbai (BOM)-Chhatrapati Shivaji International Airport'},
    {view_value:'Pune (PNQ)', value:'Pune (PNQ)-Pune International Airport'},
    {view_value:'Varanasi (VNS)', value:'Varanasi (VNS)-Lal Bahadur Shastri International Airport'},
    {view_value:'Ahmedabad (AMD)', value:'Ahmedabad (AMD)-Sardar Vallabhbhai Patel International Airport'},
    {view_value:'Bhopal (BHO)', value:'Bhopal (BHO)-Raja Bhoj Airport'},
    {view_value:'Gwalior (GWL)', value:'Gwalior (GWL)-Gwalior Airport'},
    {view_value:'Indore (IDR)', value:'Indore (IDR)-Devi Ahilya Bai Holkar Airport'},
    {view_value:'Jammu (IXJ)', value:'Jammu (IXJ)-Jammu Airport'},
    {view_value:'Lucknow (LKO)', value:'Lucknow (LKO)-Chaudhary Charan Singh International Airport'},
    {view_value:'Goa (GOI)', value:'Goa (GOI)-Goa International Airport'},
    {view_value:'Kanpur (KNU)', value:'Kanpur (KNU)-Chakeri Airport'},
    {view_value:'Kozhikode (CCJ)', value:'Kozhikode (CCJ)-Calicut International Airport'},
    {view_value:'Madurai (IXM)', value:'Madurai (IXM)-Madurai International Airport'},
    {view_value:'Nagpur (NAG)', value:'Nagpur (NAG)-Dr. Babasaheb Ambedkar International Airport'},
    {view_value:'Shillong (SHL)', value:'Shillong (SHL)-Shillong Airport'},
    {view_value:'Udaipur (UDR)', value:'Udaipur (UDR)-Maharana Pratap Airport'},
    {view_value:'Visakhapatnam (VTZ)', value:'Visakhapatnam (VTZ)-Visakhapatnam International Airport'},
    {view_value:'Shirdi (SAG)', value:'Shirdi (SAG)-Shirdi International Airport'},
    {view_value:'Kolkata (CCU)', value:'Kolkata (CCU)-Netaji Subhash Chandra Bose International Airport'},
    {view_value:'Surat (STV)', value:'Surat (STV)-Surat International Airport'},
    {view_value:'Raipur (RPR)', value:'Raipur (RPR)-Swami Vivekananda International Airport'},
    {view_value:'Bagdogra (IXB)', value:'Bagdogra (IXB)-Bagdogra Airport'},
    {view_value:'Leh Airport (IXL)', value:'Leh Airport (IXL)-Kushok Bakula Rimpochee Airport'},

]